language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - pypy

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r requirements.txt

script:
  - coverage erase
  - coverage run setup.py test
  - coverage report

after_success:
  coveralls --verbose
