language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - pypy

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.cache/pip

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage erase
  - coverage run setup.py test
  - coverage report

after_success:
  coveralls --verbose
