language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6
  - pypy

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  coverage run setup.py test

after_success:
  coveralls
